<a href="https://colab.research.google.com/github/aleksisnich/python_course/blob/master/%D0%9A%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head(20)

   whoAmI
0   robot
1   robot
2   robot
3   robot
4   human
5   robot
6   robot
7   human
8   human
9   robot
10  human
11  human
12  robot
13  human
14  human
15  human
16  robot
17  human
18  robot
19  human

In [9]:
pd.get_dummies(data['whoAmI'])

    human  robot
0    True  False
1   False   True
2    True  False
3   False   True
4    True  False
5   False   True
6   False   True
7   False   True
8    True  False
9   False   True
10  False   True
11   True  False
12   True  False
13  False   True
14  False   True
15   True  False
16   True  False
17  False   True
18   True  False
19   True  False

In [10]:
data.loc[data['whoAmI'] == 'robot', 'ROBOT'] = '1'
data.loc[data['whoAmI'] != 'robot', 'ROBOT'] = '0'
data.loc[data['whoAmI'] == 'human', 'HUMAN'] = '1'
data.loc[data['whoAmI'] != 'human', 'HUMAN'] = '0'
del data['whoAmI']
data.head()

  ROBOT HUMAN
0     1     0
1     1     0
2     1     0
3     1     0
4     0     1